### ISSUE TITLE
Equipment Error (On enter server)

### ISSUE THREAD

**Issue by smartse0k** [SkelletonX/GrandChaseIV#2]
**In line 218, Character.cs
< original >**
Database.Query(ref ds2, "SELECT   `itemID` FROM  `gc`.`equipment` WHERE `LoginUID` = '{0}' AND `CharType` = '{1}' AND `ItemUID` = '{2}'", cs.LoginUID, MyChar[MyCharPos].CharType, type);
**< fix to >**
Database.Query(ref ds2, "SELECT   `itemID` FROM  `gc`.`equipment` WHERE `LoginUID` = '{0}' AND `CharType` = '{1}' AND `ItemUID` = '{2}'", cs.LoginUID, MyChar[MyCharPos].CharType, ItemUID);

**In line 222, Character.cs
< original >**
Database.Query(ref ds, "INSERT INTO `gc`.`equipment` (  `LoginUID`,  `CharType`,  `ItemType`,  `ItemID`,`ItemUID`) VALUES  (    '{0}',    '{1}',    '{2}',    '{3}'  ,'{4}')", cs.LoginUID, MyChar[MyCharPos].CharType, type, ItemID, ItemID);
**< fix to >**
Database.Query(ref ds, "INSERT INTO `gc`.`equipment` (  `LoginUID`,  `CharType`,  `ItemType`,  `ItemID`,`ItemUID`) VALUES  (    '{0}',    '{1}',    '{2}',    '{3}'  ,'{4}')", cs.LoginUID, MyChar[MyCharPos].CharType, type, ItemID, ItemUID);

**Comment by SkelletonX** [comment]
Hi, thank you for your cooperation.

I can send you in "new pull request"

I'll add you as a developer in the repository.
