### ISSUE TITLE
PARAMETRO DO MAIN

### ISSUE THREAD

**Issue by AsunaYuno** [SkelletonX/GrandChaseIV#3]
ei cara vc pode passar o parametro do main por favor? ;^;
e esse main é da season eternal certo ?

**Comment by SkelletonX** [comment]
__kogstudios_original_service__

**Comment by SkelletonX** [comment]
" __kogstudios_original_service__ "

**Comment by SkelletonX** [comment]
https://pastebin.com/vwMSqHKB

**Comment by Raymonf** [comment]
@SkelletonX Markdown:

\`\_\_kogstudios_original_service\_\_\` => `__kogstudios_original_service__`
